#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Tmux daemon for fast startup
if [[ -z "$TMUX" ]] ;then
    ID="$( tmux ls | grep -vm1 attached | cut -d: -f1 )" # get the id of a deattached session
    if [[ -z "$ID" ]] ;then # if not available create a new one
        tmux new-session
    else
        tmux attach-session -t "$ID" # if available attach to it
    fi
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
prompt cloud '⚡'

# 10 second wait if you do something that will delete everything....
setopt RM_STAR_WAIT

# Case insensitive globbing
setopt NO_CASE_GLOB

# No need for quotes on command line arguments
setopt +o nomatch

# Disable shell scroll lock
stty -ixon

# Aliases
#alias zshconfig="mate ~/.zshrc"
#alias ohmyzsh="mate ~/.oh-my-zsh"
alias emacs='XLIB_SKIP_ARGB_VISUALS=1 emacsclient -c -a ""'
#alias emacss='~/.emacss'
#alias emacs='XLIB_SKIP_ARGB_VISUALS=1 emacs26'
alias kemacs='XLIB_SKIP_ARGB_VISUALS=1 emacsclient -e "(kill-emacs)"'
alias enw='emacs -nw'
alias ls='ls -FG'
#alias locate='mdfind'
alias cc='clang++ -std=c++14'
#alias subl='open -a Sublime\ Text'
alias scheme="rlwrap -r -c -f ~/dotfiles/scheme/mit_scheme_bindings.txt scheme"
JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"


alias zshrc='vim ~/.zshrc'
alias shellrc='vim ~/.shellrc'
alias vimrc='vim ~/.vimrc'
alias nvimrc='vim ~/.nvimrc'
alias ecask=/usr/local/opt/cask/bin/cask
alias open=pantheon-files 2>/dev/null
alias ds='xset dpms force off'
alias pip=pip2
#alias brew='sudo apt-get'

# if which jenv > /dev/null; then eval "$(jenv init -)"; fi
# export JENV_ROOT=/usr/local/var/jenv

#eval $(thefuck --alias) // slowing down zsh
# Exports
export EDITOR='vim'
export HOMEBREW_EDITOR='vim'
export ALTERNATE_EDITOR='vi'
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx
export JBOSS_HOME=/home/satya/syncron-wildfly-9.0.2.final/jboss-as

# for homebrew packages
#export PATH=$PATH:~/.cabal/bin
#export MANPATH=$MANPATH:/usr/local/opt/erlang/lib/erlang/man

# VIM for command line editing
bindkey -v
bindkey -M viins ‘jk’ vi-cmd-mode

export PATH=$HOME/node/bin:$PATH
export PATH=/snap/bin:$PATH

#export RBEN=aV_ROOT=/usr/local/var/rbenv
#export PATH=$(brew --prefix ruby)/bin:$PATH
#export PATH=/usr/local/bin:$PATH

export PATH="$HOME/.cask/bin:$PATH"

#test -e ${HOME}/.iterm2_shell_integration.zsh && source ${HOME}/.iterm2_shell_integration.zsh
#if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
#source ~/Library/Python/2.7/lib/python/site-packages/powerline/bindings/zsh/powerline.zsh

#[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
. /usr/share/autojump/autojump.zsh

# ----------------------
# Git Aliases
# ----------------------
alias gita='git add'
alias gitaa='git add .'
alias gitaaa='git add --all'
alias gitau='git add --update'
alias gitb='git branch'
alias gitbd='git branch --delete '
alias gitc='git commit'
alias gitca='git commit --amend'
alias gitcm='git commit --message'
alias gitcf='git commit --fixup'
alias gitck='git checkout'
alias gitckb='git checkout -b'
alias gitcom='git checkout master'
alias gitcos='git checkout staging'
alias gitcod='git checkout develop'
alias gitd='git diff'
alias gitdh='git diff HEAD'
alias giti='git init'
alias gitl='git log'
alias gitlg='git log --graph --oneline --decorate --all'
alias gitld='git log --pretty=format:"%h %ad %s" --date=short --all'
alias gitm='git merge --no-ff'
alias gitma='git merge --abort'
alias gitmc='git merge --continue'
alias gitp='git pull'
alias gitpr='git pull --rebase'
alias gitprom='git pull --rebase origin master'
alias gitr='git rebase'
alias gits='git status'
alias gitss='git status --short'
alias gitst='git stash'
alias gitsta='git stash apply'
alias gitstd='git stash drop'
alias gitstl='git stash list'
alias gitstp='git stash pop'
alias gitsts='git stash save'


# Python virtualenv configuration
export WORKON_HOME=$HOME/.virtualenvs
export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'

export PATH=$PATH:~/.cargo/bin

alias python="/usr/bin/python3.5"
