#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Tmux daemon for fast startup
if [[ -z "$TMUX" ]] ;then
    ID="$( tmux ls | grep -vm1 attached | cut -d: -f1 )" # get the id of a deattached session
    if [[ -z "$ID" ]] ;then # if not available create a new one
        tmux new-session
    else
        tmux attach-session -t "$ID" # if available attach to it
    fi
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
prompt cloud '⚡'

# 10 second wait if you do something that will delete everything....
setopt RM_STAR_WAIT

# Case insensitive globbing
setopt NO_CASE_GLOB

# No need for quotes on command line arguments
setopt +o nomatch

# Aliases
alias ls='ls -FG'
alias locate='mdfind'
alias cc='clang++ -std=c++17'
alias subl='open -a Sublime\ Text'

alias zshrc='vim ~/.zshrc'
alias shellrc='vim ~/.shellrc'
alias vimrc='vim ~/.vimrc'
alias nvimrc='vim ~/.nvimrc'

# Exports
export EDITOR='vim'
export HOMEBREW_EDITOR='vim'
export ALTERNATE_EDITOR='emacs'
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx

# for homebrew packages
export HOMEBREW_NO_AUTO_UPDATE=1
export PATH=:~/.cabal/bin:$PATH
export PATH=~/.cargo/bin:$PATH
export PATH=/Users/satya/.ghcup/bin:$PATH

# Python virtualenv configuration
export WORKON_HOME=$HOME/.virtualenvs
export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'


# VIM for command line editing
bindkey -v
bindkey -M viins ‘jk’ vi-cmd-mode

# autojump configuration
  [[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
. /usr/share/autojump/autojump.zsh

# ----------------------
# Git Aliases
# ----------------------
alias gita='git add'
alias gitaa='git add .'
alias gitaaa='git add --all'
alias gitau='git add --update'
alias gitb='git branch'
alias gitbd='git branch --delete '
alias gitc='git commit'
alias gitca='git commit --amend'
alias gitcm='git commit --message'
alias gitcf='git commit --fixup'
alias gitck='git checkout'
alias gitckb='git checkout -b'
alias gitcom='git checkout master'
alias gitcos='git checkout staging'
alias gitcod='git checkout develop'
alias gitd='git diff'
alias gitdh='git diff HEAD'
alias giti='git init'
alias gitl='git log'
alias gitlg='git log --graph --oneline --decorate --all'
alias gitld='git log --pretty=format:"%h %ad %s" --date=short --all'
alias gitm='git merge --no-ff'
alias gitma='git merge --abort'
alias gitmc='git merge --continue'
alias gitp='git pull'
alias gitpr='git pull --rebase'
alias gitprom='git pull --rebase origin master'
alias gitr='git rebase'
alias gits='git status'
alias gitss='git status --short'
alias gitst='git stash'
alias gitsta='git stash apply'
alias gitstd='git stash drop'
alias gitstl='git stash list'
alias gitstp='git stash pop'
alias gitsts='git stash save'



# ----------------------
#   functions
# ----------------------
##? pfd - Print the frontmost Finder directory.
function pfd {
osascript 2> /dev/null <<EOF
  tell application "Finder"
    return POSIX path of (target of first window as text)
  end tell
EOF
}

# cdf
alias cdf='cd $(pfd)'
